/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=v11d --include-runtime=false` (hash: e7849ca8f74168c1827049ae97b735ab)
interface __BaseEnv_Env {
	M2_EVENTS: D1Database;
	WEBSITE_ORIGIN: "http://127.0.0.1:4173";
	APNS_PRIVATE_KEY: string;
	APNS_KEY_ID: string;
	APNS_TEAM_ID: string;
	APNS_TOPIC: string;
	APNS_DEVICE_TOKEN: string;
	M1_TRIGGER_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEBSITE_ORIGIN" | "APNS_PRIVATE_KEY" | "APNS_KEY_ID" | "APNS_TEAM_ID" | "APNS_TOPIC" | "APNS_DEVICE_TOKEN" | "M1_TRIGGER_TOKEN">> {}
}
